# Generated by Django 4.0.4 on 2022-05-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_mobile', models.CharField(max_length=10)),
            ],
        ),
    ]
