# Generated by Django 4.0.4 on 2022-05-31 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Aadhar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.TextField()),
                ('aadhar_no', models.TextField(max_length=12)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aadhar', to='one_to_one.person')),
            ],
        ),
    ]
